#!/bin/bash

self(){
  DIR=$( cd "$( dirname "$0" )/" && pwd)
  echo $DIR
}

$(self)/down

WSPORT=80

CUSTOMPORT=$(echo $1|egrep "^[0-9]+$"|wc -l)

if [[ "$CUSTOMPORT" -gt "0" ]]; then
    WSPORT=$1
fi

# note: port designations
# 80     websocket public api
# 5005   rpc public api
# 6006   websocket admin api
# 51235  peer

# run container
docker run \
    -dit \
    --name rippled \
    -p $WSPORT:80 \
    -p 5005:5005 \
    -p 6006:6006 \
    -p 51235:51235 \
    -v $(self)/../config:/config/ \
    rippled:latest -a --start 

docker logs -f rippled
